/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/schema.json
export type Tag = {
  _id: string
  _type: "tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type CategoryReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "category"
}

export type TagReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "tag"
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description: string
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href: string
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: "image"
        _key: string
      }
    | {
        language?: string
        code: string
        _type: "codeBlock"
        _key: string
      }
  >
  category: CategoryReference
  tags: Array<
    {
      _key: string
    } & TagReference
  >
  publishedAt: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: "image"
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Tag
  | SanityImageAssetReference
  | CategoryReference
  | TagReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: {  "posts": *[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && ($q == "" || title match $pattern || description match $pattern) && (count($tags) == 0 || ($tagMode == "any" && count(tags[@->slug.current in $tags]) > 0) || ($tagMode == "all" && count(array::unique(tags[]->slug.current)[@ in $tags]) == count($tags)))] | order(publishedAt desc, _id asc) [$start...$end] {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)])},  "total": count(*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && ($q == "" || title match $pattern || description match $pattern) && (count($tags) == 0 || ($tagMode == "any" && count(tags[@->slug.current in $tags]) > 0) || ($tagMode == "all" && count(array::unique(tags[]->slug.current)[@ in $tags]) == count($tags)))])}
export type POSTS_QUERY_RESULT = {
  posts: Array<{
    _id: string
    title: string
    slug: string
    description: string
    createdAt: string
    publishedAt: string
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: "image"
    } | null
    category: {
      title: string
      slug: string
    }
    tags: Array<{
      _id: string
      title: string
      slug: string
    }>
    minRead: number | 1
  }>
  total: number
}

// Source: sanity/lib/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now())] | order(publishedAt desc, _id asc) {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)])}
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  description: string
  createdAt: string
  publishedAt: string
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: "image"
  } | null
  category: {
    title: string
    slug: string
  }
  tags: Array<{
    _id: string
    title: string
    slug: string
  }>
  minRead: number | 1
}>

// Source: sanity/lib/queries.ts
// Variable: TAGS_QUERY
// Query: *[_type == "tag" && defined(slug.current) && count(*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && references(^._id)]) > 0] | order(title asc) {_id, title, "slug": slug.current}
export type TAGS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && slug.current == $slug][0] {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)]), content}
export type POST_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  description: string
  createdAt: string
  publishedAt: string
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: "image"
  } | null
  category: {
    title: string
    slug: string
  }
  tags: Array<{
    _id: string
    title: string
    slug: string
  }>
  minRead: number | 1
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href: string
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | {
        language?: string
        code: string
        _type: "codeBlock"
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt: string
        caption?: string
        _type: "image"
        _key: string
      }
  >
} | null

// Source: sanity/lib/queries.ts
// Variable: SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now())] {"slug": slug.current}
export type SLUGS_QUERY_RESULT = Array<{
  slug: string
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "posts": *[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && ($q == "" || title match $pattern || description match $pattern) && (count($tags) == 0 || ($tagMode == "any" && count(tags[@->slug.current in $tags]) > 0) || ($tagMode == "all" && count(array::unique(tags[]->slug.current)[@ in $tags]) == count($tags)))] | order(publishedAt desc, _id asc) [$start...$end] {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)])},\n  "total": count(*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && ($q == "" || title match $pattern || description match $pattern) && (count($tags) == 0 || ($tagMode == "any" && count(tags[@->slug.current in $tags]) > 0) || ($tagMode == "all" && count(array::unique(tags[]->slug.current)[@ in $tags]) == count($tags)))])\n}': POSTS_QUERY_RESULT
    '*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now())] | order(publishedAt desc, _id asc) {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)])}': ALL_POSTS_QUERY_RESULT
    '*[_type == "tag" && defined(slug.current) && count(*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && references(^._id)]) > 0] | order(title asc) {_id, title, "slug": slug.current}': TAGS_QUERY_RESULT
    '*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now()) && slug.current == $slug][0] {_id, title, "slug": slug.current, description, "createdAt": _createdAt, publishedAt, coverImage, "category": category->{title, "slug": slug.current}, "tags": tags[]->{_id, title, "slug": slug.current}, "minRead": math::max([1, round(length(pt::text(content)) / 5 / 200)]), content}': POST_QUERY_RESULT
    '*[_type == "post" && defined(slug.current) && defined(publishedAt) && dateTime(publishedAt) <= dateTime(now())] {"slug": slug.current}': SLUGS_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
